# Note: libasynql is placed above PoolExample so that libasynql is built before PoolExample. This ensures that the latest version of libasynql is used to infect PoolExample.
projects:
  libasynql:
    type: library
    model: virion
    path: libasynql
  PoolExample:
    path: examples/PoolExample
    libs:
      - src: /libasynql
        version: ^2.0
        # shade: syntax
        # format: virion
        # vendor: poggit-project

# possible shade strategies:
#   syntax (use token_get_all() to scan all syntactical references)
#   single (use str_replace(); will also replace single-quoted references)
#   double (use str_replace() with \ and \\; will also replace double-quoted references

# possible formats: virion
# planning to add composer too

# possible vendors: poggit-project, raw
